# ArgoCD Application for MyBank Services
# This configures ArgoCD to automatically deploy and sync the microservices chart

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mybank-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    tier: backend
    environment: development
spec:
  project: default

  source:
    repoURL: https://github.com/your-org/mybank.git
    targetRevision: HEAD
    path: helm/services

    helm:
      releaseName: mybank-services
      valueFiles:
        - values.yaml
      values: |
        global:
          namespace: mybank
          environment: development
          imagePullPolicy: IfNotPresent
        common:
          replicas: 1
        services:
          apiGateway:
            enabled: true
            replicas: 2
          authService:
            enabled: true
            replicas: 2
          userService:
            enabled: true
            replicas: 2
          assetService:
            enabled: true
            replicas: 2
          analyticsService:
            enabled: true
            replicas: 2
          paymentService:
            enabled: true
            replicas: 2
          investmentService:
            enabled: true
            replicas: 2

  destination:
    server: https://kubernetes.default.svc
    namespace: mybank

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Wait for infrastructure to be healthy before syncing services
  info:
    - name: 'Depends on'
      value: 'mybank-infrastructure'

  revisionHistoryLimit: 10
